Allow tlmgr errors, thanks to updmap weirdness

diff --git a/build/default/Dockerfile b/build/default/Dockerfile
--- a/build/default/Dockerfile
+++ b/build/default/Dockerfile
@@ -36,10 +36,11 @@ RUN /usr/lib/R/site-library/littler/examples/installGithub.r ${BUILD_R_GITHUB_DE
 
 ### Setup TeX packages
 RUN tlmgr init-usertree
-RUN tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2017/tlnet-final/
+RUN tlmgr --usermode option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2017/tlnet-final/
 
 ARG BUILD_TEX_DEPENDENCIES="framed printlen pgf draftwatermark everypage lastpage enumitem sectsty xcharter"
-RUN tlmgr install ${BUILD_TEX_DEPENDENCIES}
+RUN tlmgr --usermode install ${BUILD_TEX_DEPENDENCIES} || echo "updmap errors are okay?!"
+RUN updmap-user
 
 ### Cleanup to reduce size of the image
 RUN apt-get remove -y -qq ${DOCKER_APT_DEPENDENCIES}
